### ISSUE TITLE
stt is not a funtion

### ISSUE THREAD

**Issue by Zames-Chang** [wechaty/stt#17]
i clone your test folder and do
```
npm install stt
```
and here is my app.js
did i miss something?
```js
const stt = require('stt')
var fs = require('fs')
const speechStream = fs.createReadStream('./test/fixture/测试.mp3')

stt(speechStream).then(text => {
    console.log('STT: ' + text)
})
```

error message
```
stt(speechStream).then(text => {
^

TypeError: stt is not a function
    at Object.<anonymous> (/home/summer2017/user/e44041034/speech/app.js:5:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by vecchiotom** [comment]
change `const stt = require('stt')` to `const stt = require('stt').stt`
